name: "TD-1-samples"
# mattergen_path: "/data/user/reents_t/projects/mlip/git/diffusion-based-crystal-structure-inpainting/"
fix_cell: true
max_num_atoms: 20
predictor_corrector: "new-timesteps"
param_grid:
  N_structures: -1
  N_steps: 50
  coordinates_snr: [0.2]
  n_corrector_steps: [1]
  batch_size: 500
  N_samples_per_structure: 1
relax_kwargs:
  load_path: "MatterSim-v1.0.0-5M.pth"
  fmax: 0.0025
# pretrained_name: "mattergen_base"
model_path: "/data/user/reents_t/projects/mlip/git/mattergen/checkpoints/new-td-20-perc"
save_prefix: "TD-1-samples"